### ISSUE TITLE
Create SA Menu page with Post Shift logic

### ISSUE THREAD

**Issue by meetsriharsha** [SCE-UMKC/ASESP16_StudentCompanion_Team7#20]

**Comment by meetsriharsha** [comment]
@rajkiranreddym: Please provide updated code. Hope you completed most of the task

**Comment by meetsriharsha** [comment]
@rajkiranreddym: Try to work on Post substitution part. I've completed the Take shift part

**Comment by rajkrm** [comment]
Developed the required functionality.
