### ISSUE TITLE
Create class, sequence and state chart diagrams

### ISSUE THREAD

**Issue by meetsriharsha** [SCE-UMKC/ASESP16_StudentCompanion_Team7#7]
Create diagrams for the Student Companion application

**Comment by rajkrm** [comment]
I have been working on state chart diagram.Done with class and sequence diagrams.

**Comment by rajkrm** [comment]
I am completed the task assigned

**Comment by meetsriharsha** [comment]
Included the diagrams in the document and submitted the document.
Hence closing.
